name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  

  Android:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        pwd
        cd Xamarin.TravelCostsReport/Mobile   
        nuget restore
        cd TravelingCostsReport.Android 
        msbuild TravelingCostsReport.Android.csproj /t:Rebuild /p:Configuration=Release

