name: Core

on:
  push:
    paths-ignore:
    - 'Xamarin.TravelCostsReport/Mobile/TravelingCostsReport.Android/**'
  pull_request:
    paths: 
    - 'Xamarin.TravelCostsReport/Mobile/TravelingCostsReport.Android/**'
     
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:

  NetStandards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          
      - name: Restore dependencies
        run: |
          cd Xamarin.TravelCostsReport
          dotnet restore Xamarin.TravelCostsReport.sln
          
      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            dotnet sonarscanner begin /k:"zanuccod_Xamarin.TravelCostsReport" /o:"zanuccod" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
            dotnet build Xamarin.TravelCostsReport/BusinnesLogic/BusinnesLogic --no-restore
            dotnet build Xamarin.TravelCostsReport/Core/Core --no-restore
            dotnet build Xamarin.TravelCostsReport/Mobile/TravelingCostsReport --no-restore
            dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Test and Coverage
        run: 
          echo test and coverage
