name: Droid

on:
  push:
    paths: 
    - 'Xamarin.TravelCostsReport/Mobile/TravelingCostsReport.Android/**'
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
        
jobs:
  Android:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Android
      run: |
        cd Xamarin.TravelCostsReport
        nuget restore
        msbuild Mobile/TravelingCostsReport.Android/TravelingCostsReport.Android.csproj /t:Rebuild /p:Configuration=Release
